version: 0.2

env:
  variables:
    ECR_REPOSITORY: 533267135387.dkr.ecr.ap-northeast-1.amazonaws.com/test-ecr
  secrets-manager:
    DOCKERHUB_USER: arn:aws:secretsmanager:ap-northeast-1:533267135387:secret:docker-hub-credentials-eoOVZJ:username
    DOCKERHUB_PASS: arn:aws:secretsmanager:ap-northeast-1:533267135387:secret:docker-hub-credentials-eoOVZJ:accessToken

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${ECR_REPOSITORY}
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASS | docker login --username $DOCKERHUB_USER --password-stdin
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t container-test-app .
      - docker tag container-test-app:latest ${ECR_REPOSITORY}:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push ${ECR_REPOSITORY}:latest
      - echo Build completed on `date`
      - echo Creating imagedefinitions.json...
      - |
        echo '[
          {
            "name": "container-test-app",
            "imageUri": "'${ECR_REPOSITORY}':latest"
          }
        ]' > imagedefinitions.json
      - echo imagedefinitions.json created.

artifacts:
  files:
    - imagedefinitions.json
