version: 0.2

env:
  variables:
    ECR_REPO_NAME: api-repository
  secrets-manager:
    DOCKERHUB_USER: arn:aws:secretsmanager:ap-northeast-1:533267135387:secret:docker-hub-credentials-eoOVZJ:username
    DOCKERHUB_PASS: arn:aws:secretsmanager:ap-northeast-1:533267135387:secret:docker-hub-credentials-eoOVZJ:accessToken

phases:
  pre_build:
    commands:
      - echo "hello"

      #ECR login
      - ECR_MAIN_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_MAIN_URI}
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASS | docker login --username $DOCKERHUB_USER --password-stdin

      - ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPO_NAME}:${CODEBUILD_RESOLVED_SOURCE_VERSION:0:8}"
      # - ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPO_NAME}:latest"
  build:
    commands:
      - docker build --platform linux/x86_64 -t ${ECR_REPO_NAME}:latest .
  post_build:
    commands:
      - docker tag ${ECR_REPO_NAME}:latest ${ECR_IMAGE_URI}
      - docker push ${ECR_IMAGE_URI}
      # - printf '[{"name":"sprint-container","imageUri":"%s"}]' ${ECR_IMAGE_URI} > imagedefinitions.json
      - printf '{"ImageURI":"%s"}' ${ECR_IMAGE_URI} > imageDetail.json

artifacts:
  files:
    # - imagedefinitions.json
    - appspec.yml
    - taskdef.json
    - imageDetail.json
